<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>TechnicalInspection.PoC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TechnicalInspection.PoC.Domain\TechnicalInspection.PoC.Domain.csproj" />
    <ProjectReference Include="..\TechnicalInspection.PoC.TestBase\TechnicalInspection.PoC.TestBase.csproj" />
  </ItemGroup>

</Project>
